# 序列构成的数组

In [1]:
symbols = '$¢£¥€¤'
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

codes    

[36, 162, 163, 165, 8364, 164]

In [2]:
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

In [3]:
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 163, 165, 8364, 164]

In [4]:
beyond_ascii = list(filter(lambda c: c>127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

In [5]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [6]:
for color in colors:
    for size in sizes:
        print(color, size)

black S
black M
black L
white S
white M
white L


In [7]:
tshirts = [(color, size) for size in sizes for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [8]:
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [9]:
import array

array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [10]:
for tshirts in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirts)

black S
black M
black L
white S
white M
white L


In [11]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [12]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [13]:
latitude, longitude = lax_coordinates
latitude

33.9425

In [14]:
longitude

-118.408056

In [15]:
divmod(20, 8)

(2, 4)

In [16]:
t = (20, 8)
divmod(*t)

(2, 4)

In [17]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [18]:
import os 

_, filename = os.path.split('/home/wangheng/ml/FP_CH01.ipynb')
filename

'FP_CH01.ipynb'

In [19]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [20]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [21]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [22]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [23]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [24]:
metro_areas = [('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
               ('Delhi NCR', 'IN', 21.953, (28.613889, 77.208889)),
               ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
               ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
               ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833))]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [25]:
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [26]:
tokyo.population

36.933

In [27]:
tokyo.coordinates

(35.689722, 139.691667)

In [28]:
tokyo[1]

'JP'

In [29]:
City._fields

('name', 'country', 'population', 'coordinates')

In [30]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.953, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.953,
 'coordinates': LatLong(lat=28.613889, long=77.208889)}

In [31]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.953
coordinates: LatLong(lat=28.613889, long=77.208889)


In [32]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [33]:
l[2:]

[30, 40, 50, 60]

In [34]:
l[:3]

[10, 20, 30]

In [35]:
l[3:]

[40, 50, 60]

In [36]:
s = 'bicycle'
s[:3]

'bic'

In [37]:
s[::-1]

'elcycib'

In [38]:
s[::-2]

'eccb'

In [39]:
invoice = '''
0.....6..................................40..........52..55....
1909  Pimoroni PiBrella                  $17.50      3   $52.50
1489  6mm Tactile Switch x20              $4.95      2    $9.90
1510  Panavise Jr. - PV-201              $28.00      1   $28.00
1601  PiTFT Mini Kit 320x240             $34.95      1   $34.95 
'''

SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

 $17.50      Pimoroni PiBrella                 
  $4.95      6mm Tactile Switch x20            
 $28.00      Panavise Jr. - PV-201             
 $34.95      PiTFT Mini Kit 320x240            
 


In [40]:
invoice.split('\n')[2:]

['1909  Pimoroni PiBrella                  $17.50      3   $52.50',
 '1489  6mm Tactile Switch x20              $4.95      2    $9.90',
 '1510  Panavise Jr. - PV-201              $28.00      1   $28.00',
 '1601  PiTFT Mini Kit 320x240             $34.95      1   $34.95 ',
 '']

In [41]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [43]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [44]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [45]:
l[2:5] = 100

TypeError: can only assign an iterable

In [46]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [47]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [48]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [49]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [50]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [51]:
werid_board = [['_'] * 3] * 3
werid_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [52]:
werid_board[1][2] = '0'
werid_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [53]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

In [54]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [55]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [56]:
l = [1, 2, 3]
id(l)

140197262481152

In [57]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [58]:
id(l)

140197262481152

In [59]:
t = (1, 2, 3)
id(t)

140197262475328

In [60]:
t *= 2
id(t)

140197262799680

In [61]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [62]:
t

(1, 2, [30, 40, 50, 60])

In [63]:
import dis

dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


In [64]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [65]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [66]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [67]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [68]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [69]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [70]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [71]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'


def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

if __name__ == '__main__':
    
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
         bisect_fn = bisect.bisect
            
    print('DEMO:', bisect_fn.__name__)        
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [72]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]


[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [73]:
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [74]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5963321947530882

In [75]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [76]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
floats2[-1]

0.5963321947530882

In [77]:
floats2 == floats

True

In [78]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [79]:
memv[0]

-2

In [80]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [81]:
memv_oct[5] = 4
memv_oct.tolist()

[254, 255, 255, 255, 0, 4, 1, 0, 2, 0]

In [82]:
numbers

array('h', [-2, -1, 1024, 1, 2])

In [83]:
import numpy as np

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
type(a)

numpy.ndarray

In [85]:
a.shape

(12,)

In [86]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a[2]

array([ 8,  9, 10, 11])

In [88]:
a[2, 1]

9

In [89]:
a[:, 1]

array([1, 5, 9])

In [90]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [91]:
from random import uniform

floats3 = [str(uniform(100000, 5000000)) for i in range(10**3)]

for i in range(len(floats3)):
    floats3[i] += '\n'

In [92]:
with open('floats-10M-lines.txt', 'w') as fp:
    fp.writelines(floats3)

In [93]:
floats = np.loadtxt('floats-10M-lines.txt')
floats[-3:]

array([1601517.74960952, 1093060.11577102,  322066.50840193])

In [94]:
floats *= .5
floats[-3:]

array([800758.87480476, 546530.05788551, 161033.25420097])

In [95]:
from time import perf_counter as pc

t0 = pc()
floats /= 3
pc() - t0

4.617200102075003e-05

In [96]:
np.save('floats-10M', floats)

In [97]:
floats2 = np.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([1601517.74960952, 1093060.11577102,  322066.50840193])

In [98]:
from collections import deque

dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [100]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [101]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [103]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

In [104]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]
sorted(l)

TypeError: '<' not supported between instances of 'str' and 'int'

In [105]:
sorted(l, key=int)

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']

In [106]:
sorted(l, key=str)

[0, '1', 14, 19, '23', 28, '28', 5, 6, '9']